module.exports = {
	async list() {
		const weaponlist = {                                                
    "arming sword": "weapon_armingsword",                        
    "assault rifle": "weapon_assaultrifle",                      
    "auto shotgun": "weapon_autoshotgun",
    "amr": "weapon_antimaterielrifle",
    "battleaxe": "weapon_battleaxe",                             
    "bazooka": "weapon_bazooka",                                 
    "bow": "weapon_bow",                                         
    "bullpup rifle": "weapon_bullpuprifle",                      
    "bullpup smg": "weapon_bullpupsmg",                          
    "charged longsword": "weapon_chargedlongsword",              
    "crystal kalis": "weapon_crystalkalis",                      
    "derringer": "weapon_derringer",                             
    "flintlock pistol": "weapon_flintlockpistol",                
    "grenade launcher": "weapon_grenadelauncher",                
    "handaxe": "weapon_handaxe",                                 
    "health potion": "weapon_healthpotion",                      
    "classic assault rifle": "weapon_heavyassaultrifle",         
    "heavy smg": "weapon_heavysmg",                              
    "hero sword": "weapon_herosword",                            
    "high power pistol": "weapon_highpowerpistol",               
    "holo blade": "weapon_holoblade",                            
    "hunting shotgun": "weapon_huntingshotgun",                  
    "ikakalaka": "weapon_ikakalaka",                             
    "impact grenade": "weapon_impactgrenade",                    
    "impact grenade launcher": "weapon_impactgrenadelauncher",   
    "impulse grenade": "weapon_impulsegrenade",                  
    "khopesh": "weapon_khopesh",                                 
    "knife": "weapon_knife",                                     
    "lever action rifle": "weapon_leveractionrifle",             
    "light machine gun": "weapon_lightmachinegun",               
    "long sword": "weapon_longsword",                            
    "magnum pistol": "weapon_magnumpistol",                      
    "micro smg": "weapon_microsmg",                              
    "minigun": "weapon_minigun",                                 
    "pistol": "weapon_pistol",                                   
    "pulse carbine": "weapon_pulsecarbine",                      
    "barrage launcher": "weapon_quadlauncher",                   
    "revolver": "weapon_revolver",                               
    "rocket jumper": "weapon_rocketjumper",                      
    "rocket launcher": "weapon_rocketlauncher",
    "sabre": "weapon_sabre",
    "semi auto rifle": "weapon_semiautorifle",
    "service rifle": "weapon_servicerifle",
    "shotgun": "weapon_shotgun",
    "slug shotgun": "weapon_slugshotgun",
    "sniper": "weapon_sniper",
    "spatha": "weapon_spatha",
    "smg": "weapon_standardsubmachinegun",
    "stick grenade": "weapon_stickgrenade",
    "suppressed smg": "weapon_submachinegun",
    "super shotgun": "weapon_supershotgun",
    "suppressed assault rifle": "weapon_suppressedassaultrifle",
    "suppressed bullpup smg": "weapon_suppressedbullpupsmg",
    "suppressed pistol": "weapon_suppressedpistol",
    "suppressed service rifle": "weapon_suppressedservicerifle",
    "tactical shotgun": "weapon_tacticalshotgun",
    "tactical smg": "weapon_tacticalsmg",
    "tomahawk": "weapon_tomahawk",
    "twin cannon": "weapon_twincannon",
    "typewriter smg": "weapon_typewritersmg",
    "zweihander": "weapon_zweihander"
		};
		return weaponlist;
	}
}